CREATE TABLE USER( 
	PK          INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USERNAME	VARCHAR2(100) NOT NULL,
	PASSWORD	VARCHAR2(100) NOT NULL,
	CLOUDKEY	VARCHAR2(100),
	CLOUDPWD	VARCHAR2(100),
	SSHKEY		VARCHAR2(100),
	SSHPUB		VARCHAR2(100),
	ADMIN		BOOLEAN
);

CREATE TABLE CLUSTER( 
	PK          	INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME			VARCHAR2(100) NOT NULL,
	IDENTIFIER		VARCHAR2(100) NOT NULL,
	CLOUD_USERNAME	VARCHAR2(100) NOT NULL,
	ADDRESS			VARCHAR2(100),
	INSTANCE_TYPE	VARCHAR2(100),
	KEY_AVAILABLE	BOOLEAN,
	KEY_SEC			VARCHAR2(100),
	KEY_PUB			VARCHAR2(100),
	AMOUNT			VARCHAR2(100),
	STATE			INTEGER,
	LOG				VARCHAR2(255),
	CREATION_TIME	LONG,
	CLIENT_ID 		INTEGER NOT NULL REFERENCES USER(PK)
);

